### ISSUE TITLE
[Feature Request] Publish to PowerShell Gallery 

### ISSUE THREAD

**Issue by rashil2000** [zhoujin7/scoop-search#1]
First of all, thank you for creating this! I have many buckets installed and the in-built search is hella slow. Your app not only searches installed buckets but searches all buckets on GitHub! And is super fast. 

Assuming you are familiar with PowerShell modules and PowerShell Gallery, it would be a nice idea to publish your project there. It will make installation and usage super easy, and will also help in case you plan on extending the API with more search parameters.

**Comment by rashil2000** [comment]
Also, it'd be better if the output of `scoopSearch.ps1` is (array of) objects. It becomes easier to consume that way. Currently it just outputs strings.

**Comment by rashil2000** [comment]
Here, I've created the function for you :)

```powershell
Function Find-Scoop {
  param([Parameter(Mandatory = $true)][string]$appName)

  $searchResults = (Invoke-RestMethod -URI 'https://scoop.zhoujin7.com/search' -Method Post -ContentType 'application/json' -Body (ConvertTo-Json @{ app_name = $appName })).Split([Environment]::NewLine)
  $resArray = @()
  for ($i = 1; $i -lt $searchResults.Length; $i++) {
    $details = ($searchResults[$i] -replace '\s+', ' ').split('')
    $resArray += [pscustomobject]@{
      Name = $details[0];
      Version = $details[1];
      Bucket = $details[2]
    }
  }
  return $resArray
}
```

**Comment by zhoujin7** [comment]
Thanks. But I'm too lazy to do it.
