### ISSUE TITLE
Out of date results

### ISSUE THREAD

**Issue by rashil2000** [zhoujin7/scoop-search#2]
While the sqlite database in your crawl-scoop-directory repository gets updated daily, the endpoint here is not showing up to date results. For example, viewing your scoop-directory.db file in SQLiteBrowser and searching for 'Clink' shows up 3 results with latest versions, your endpoint only shows 2 out-of-date results.

**Comment by zhoujin7** [comment]
Network reasons, the data was not synchronized successfully in time.
